spring.application.name=api-gateway

server.port=8080


# =========================
# MS PACIENTES
# =========================
spring.cloud.gateway.mvc.routes[0].id=ms-pacientes
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/pacientes/**


# =========================
# MS AGENDA - CITAS
# =========================
spring.cloud.gateway.mvc.routes[1].id=ms-citas
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/citas/**


# =========================
# MS AGENDA - MEDICOS
# =========================
spring.cloud.gateway.mvc.routes[2].id=ms-medicos
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/medicos/**


# =========================
# MS HISTORIAL
# =========================
spring.cloud.gateway.mvc.routes[3].id=ms-historial
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/historial/**


# =========================
# MS AUDITORIA
# =========================
spring.cloud.gateway.mvc.routes[4].id=ms-auditoria
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/auditoria/**
