# Base de datos en memoria para la interfaz de usuario
spring.datasource.url=jdbc:h2:mem:historial;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA para desarrollo local de UI
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Desactiva el server web cuando se inicia desde la UI
spring.main.web-application-type=none
